### ISSUE TITLE
OSX 'Unable to parse configuration'

### ISSUE THREAD

**Issue by uptownhr** [mmastrac/stylus#2]
```
thread 'main' panicked at 'Unable to parse configuration: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:69:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I followed the docker example and also from the sh manually. 

My directory being mounted looks like
-config.yml
-monitor.d
-- dns
---config.yaml
---dns.sh

STR.
1. docker run --rm -it -p 8000:8000 -v $PWD:/srv mmastrac/stylus:latest sh
2. I can confirm /srv has my files
3. running stylus `stylus srv/config.yaml` results in the error mentioned above.

**Comment by mmastrac** [comment]
Thanks for the report! I'm assuming the file in the root is called `config.yaml` and not `config.yml`. 

To confirm, you are running Docker on OSX?

Could you try the following just to rule out possible problems:

  1. Download the git repo and unzip it somewhere
  2. Run the following: `docker run --rm -it -p 8000:8000 -v (path to the example config.yaml):/srv mmastrac/stylus:latest sh`
  3. If that works, try replacing `$PWD` in your command above with the absolute path to your config folder.

**Comment by mmastrac** [comment]
I confirmed that the following worked locally on my machine with a GH repo:

`docker run --name stylus -it -p 8000:8000 -v /Users/matt/Documents/github/stylus/example/:/srv mmastrac/stylus:latest`

**Comment by mmastrac** [comment]
Going to mark this as closed for now, but please feel free to re-open.
