### ISSUE TITLE
could we get some releases and versions

### ISSUE THREAD

**Issue by lastlink** [mmastrac/stylus#4]
since this is rust we could get binary builds for different operating systems

**Comment by mmastrac** [comment]
@lastlink That would be great. Right now I build the binaries directly to docker. Do you have any ideas how I can automate the per-platform publishing process for statically linked binaries?

**Comment by mmastrac** [comment]
Also please note that you can run `cargo install stylus` on your target system but that requires `rustup`.

**Comment by lastlink** [comment]
usually people write like a **bash** script they run to generate all the binaries and then upload them to the github releases page

**Comment by mmastrac** [comment]
@lastlink I'm playing around with github releases and I may have something for you to try shortly.

**Comment by mmastrac** [comment]
@lastlink Give these a shot - linux only but major platforms represented: https://github.com/mmastrac/stylus/releases

**Comment by mmastrac** [comment]
Closing for now. Please re-comment and I can re-open!
